language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: required
    services:
      - docker
    python: '3.7'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m pytest --cov-report term --cov=./gtagora tests

after_success:
    - codecov